# Generated by Django 3.2.8 on 2022-01-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about_me',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Обо мне'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('U', 'Не указан')], default='U', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Тэги'),
        ),
    ]
